### ISSUE TITLE
barcode 128 support

### ISSUE THREAD

**Issue by yb123tcs** [nomadoda/react-zxing#10]
zxing supports code128. However with react-zxing only qr code works

**Comment by adamkrupke** [comment]
This package is just a wrapper of @zxing/library which should support code128 just fine (see [here](https://github.com/zxing/zxing#supported-formats)). Did you experience otherwise?

**Comment by yb123tcs** [comment]
Hi! Exactly. The QR scanned perfectly, however the 128 did not. Perhaps it has to do with auto-focus that is needed for 1D scans?
Or do you have other suggestions I can try?

**Comment by adamkrupke** [comment]
My experience with scanning one dimensional codes generally is that it is a bit more difficult when using a camera, especially when it is not well lit for example. I don't think this library should influence the capabilities of zxing itself in reading the stream. Could you try using the [zxing demo](https://zxing-js.github.io/library/) and see if you get different results?

**Comment by yb123tcs** [comment]
Hi!

Yeah I tested with the zxing demo, and indeed only QR went fine.

THanks for your help, and let me know if you can think of something else
________________________________
