### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'srcObject')

### ISSUE THREAD

**Issue by JayCabasag** [nomadoda/react-zxing#11]
This happens when using the hook inside a component, in my case its a 'react-modal',
What happen is when user opens the modal and close it without letting the video streaming started yet, this error will occur.

**Comment by adamkrupke** [comment]
Could you provide any reproduction of this? I'm trying to replicate it by mounting and unmounting the video ref, but I'm not seeing this error.

**Comment by adamkrupke** [comment]
Ah, I see it now. It happens when unmounting while or after requesting permissions.
