### ISSUE TITLE
Error when attempting to run

### ISSUE THREAD

**Issue by rhazell-msi** [nomadoda/react-zxing#12]
Hello, 

I simply cloned and for the **Example** I ran "yarn", then "yarn start" and I get the following error:

@parcel/core: Failed to resolve 'react/jsx-dev-runtime' from './src/index.tsx'

  C:\Development\React\Scanner\react-zxing-main\example\src\index.tsx:1:1
  > 1 | import React from "react";
  >   | ^
    2 | import ReactDOM from "react-dom/client";
    3 | import App from "./App";

Any idea what might be the cause?

Thanks in advance.

**Comment by adamkrupke** [comment]
Hi! I'm not entirely sure, but I added some documentation on how to get the example running for local development. Please follow the newly added README instructions and see if it works. What node version are you on?

**Comment by adamkrupke** [comment]
Closing for now, but please let me know if you're still having this issue!
