### ISSUE TITLE
react-zxing scans both QR-code & barcode

### ISSUE THREAD

**Issue by abhishekdigitech** [nomadoda/react-zxing#13]
By default, react-zxing scans both QR-code & barcode.    
Is there a way to scan only one thing ?

**Comment by adamkrupke** [comment]
Yes, you may pass this using the hints option property. For example:

```tsx
import { BarcodeFormat, DecodeHintType } from "@zxing/library";
import { useZxing } from "react-zxing";

const hints = new Map();
const formats = [BarcodeFormat.QR_CODE, BarcodeFormat.DATA_MATRIX /*, ...*/];

hints.set(DecodeHintType.POSSIBLE_FORMATS, formats);

export const BarcodeScanner: React.FC<{}> = () => {
  const { ref } = useZxing({
    hints,
  });
  return <video ref={ref} />
});
```

[See @zxing/library](https://github.com/zxing-js/library#usage)

**Comment by abhishekdigitech** [comment]
Thanks, my issue is resolved.
**I have one more issue :**
On my web-page, I have toggle functionality, which means the user can scan the barcode or manually enter the barcode in the input field. By default, scan mode is enabled. The problem is if I switch to manual input and then switch to scan mode, then the scan view from the web-page gone.
My code is given below :     
 
```
import { useZxing } from 'react-zxing';

const { ref } = useZxing({
        onResult(result) {
            setResult(result.getText());
        }
    });
{manualInput === false && (
<video ref={ref} />
)}

{manualInput === true && (
/*Show HTML form */
)}
```    

**Second problem is :**    
While switching tabs (scan mode or manual input), the camera doesn't turn off. (On my laptop, there is a camera indicator light which becomes ON if the camera is in use, I didn't test on the phone).     


**UI Links :**   

1. When user first time visits the page and allow camera permission : https://i.imgur.com/H5yuR6P.png
2. When user switch to manual input : https://i.imgur.com/BpylU8T.png
3. When user switch back to scan mode : https://i.imgur.com/51A890H.png
