### ISSUE TITLE
Detecting failed permission and

### ISSUE THREAD

**Issue by atengberg** [nomadoda/react-zxing#15]
Hello, great library! Thanks.

If the user refuses to grant permission, should this through an error to the error handler?

At least on Safari, instead it logs an unhandled rejection:

![Screenshot from 2023-06-02 16-55-56](https://github.com/adamalfredsson/react-zxing/assets/7552595/57e3dcbd-ebfe-4897-9168-3f113e413dbd)

Or could it be another state variable like isTorchAvailable, "isCameraAvailable"? 

---

Also on another related note I wanted to overlay some controls on the video, and I found making use of:

```javascript
  const [ready, setReady] = useState(false);
  useEffect(() => {
    // Only show overlay with controls (torch, close) once actual video stream is displayed.
    const loadedListener = (e) => setReady(true);
    if (ref.current) ref.current.addEventListener('loadeddata', loadedListener);
    return () => current?.removeEventListener('loadeddata', loadedListener);
  }, [paused]);
```
Since there's already the ref to the video in case this is helpful to anyone. 

Thanks again, one of the few react qrcode libraries that work out of the box these days.

**Comment by adamkrupke** [comment]
Released in 2.0.0!

**Comment by adamkrupke** [comment]
I will also consider your other note on listening to the `loadeddata` event. However, I'm not sure if this should be within the scope of this library.

**Comment by atengberg** [comment]
Definitely.

One recommendation I think worth adding is an alternative loader such as
file input (which could be used if permissions fail).

Great work!
