### ISSUE TITLE
videoTrack.getCapabilities is not a function in Firefox

### ISSUE THREAD

**Issue by hychanfion** [nomadoda/react-zxing#16]
Accroding to [https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities#browser_compatibility), videoTrack.getCapabilities is not supported in Firefox.

When I tried to open camera in Firefox, the console log will throw `Uncaught (in promise) TypeError: videoTrack.getCapabilities is not a function`

![image](https://github.com/adamalfredsson/react-zxing/assets/137746140/ceae3591-050f-4c7c-9d07-63d6213c0035)

Is it able to set a indicator in useZxing to bypass torch init? or any workaround to skip this error? 
Thank you.

**Comment by adamkrupke** [comment]
This should already be fixed in 1.1.3
