### ISSUE TITLE
Eanble Torch 

### ISSUE THREAD

**Issue by Aelmouny11** [nomadoda/react-zxing#6]
I would be better if there's an option to enable torch. Is it possible to enable torch externally even with the camera is ued by zxing.

**Comment by adamkrupke** [comment]
Great idea! I'll have this implemented!

**Comment by adamkrupke** [comment]
I've added this now in fad0152dfd236bbd9f3ea25735263edd93ccb991. Unfortunately it seems like torch support is fairly limited. I've added documentation on how to use it. If you could get the chance to try it out, please let me know how it works!
